// top_decoder.sv
`timescale 1ns/1ps
`include "defs.v"

module top_decoder (
  input  wire clk,
  input  wire rst_n,
  input  wire start,
  output wire done_all
);
  // parameters
  localparam int NUM_COLS = 16;
  localparam int Z        = 42;
  localparam int NUM_LAYERS = 8;
  // MSG_W: pc + sc + min1 + min2 (uses MIN_W from your defs)
  localparam int MSG_W = 1 + 1 + MIN_W + MIN_W;

  // --- Controller interfaces (assumed implemented separately) ---
  wire [$clog2(NUM_COLS)-1:0] cycle_idx;
  wire [NUM_COLS*4-1:0]      faddr_bus;
  wire [NUM_COLS-1:0]        en_slice_bus;
  reg  [NUM_COLS-1:0]        frame_done; // to be driven by parity checker

  // instantiate controller (assumes your controller has this signature)
  controller #(.NUM_COLS(NUM_COLS), .NUM_FRAMES(16)) ctrl (
    .clk(clk), .rst_n(rst_n),
    .faddr_bus(faddr_bus),
    .en_slice_bus(en_slice_bus),
    .frame_done(frame_done),
    .cycle_idx(cycle_idx)
  );

  // Flattened layer buses per column: each is Z messages of MSG_W bits
  // Outgoing messages from column c (to be routed to next column (c+1)%NUM_COLS)
  wire [Z*MSG_W-1:0] layer_bus_out_flat [NUM_COLS-1:0];
  // Incoming messages to column c (driven by routing logic)
  reg  [Z*MSG_W-1:0] layer_bus_in_flat  [NUM_COLS-1:0];

  // Instantiate column_slice modules
  genvar c;
  generate
    for (c = 0; c < NUM_COLS; c = c + 1) begin : cols
      // feed faddr and enable signals
      wire [3:0] faddr = faddr_bus[c*4 +: 4];
      wire en_slice = en_slice_bus[c];

      // instantiate column_slice (must accept flat in/out vectors)
      column_slice #(
        .COL_ID(c),
        .Z(Z),
        .QV_W(QV_W),
        .LVC_MAG(LVC_MAG),
        .LVC_W(LVC_W),
        .NFRAMES(16),
        .MEM_TYPE("BRAM")
      ) cs (
        .clk(clk),
        .rst_n(rst_n),
        .cycle_idx(cycle_idx),
        .faddr_read(faddr),
        .en_slice(en_slice),
        .in_layer_bus(layer_bus_in_flat[c]),   // flattened vector input
        .out_layer_bus(layer_bus_out_flat[c]), // flattened vector output
        .parity_bits_out() // connect to parity reduction logic outside
      );
    end
  endgenerate

  // --- Router instantiation per (col, row) ---
  // Each router is combinational: feeds local arrays router_to_row, router_active, router_inactive
  logic [$clog2(Z)-1:0] router_to_row [NUM_COLS-1:0][Z-1:0];
  logic router_active      [NUM_COLS-1:0][Z-1:0];
  logic router_inactive    [NUM_COLS-1:0][Z-1:0];

  // compute current layer from cycle index (controller-driven)
  logic [$clog2(NUM_LAYERS)-1:0] current_layer;
  assign current_layer = cycle_idx % NUM_LAYERS;

  genvar gc, gr;
  generate
    for (gc = 0; gc < NUM_COLS; gc = gc + 1) begin : gen_router_col
      for (gr = 0; gr < Z; gr = gr + 1) begin : gen_router_row
        router #(
          .NUM_COLS(NUM_COLS),
          .Z(Z),
          .NUM_LAYERS(NUM_LAYERS),
          .RATE_SELECT(RATE_SELECT) // RATE_SELECT is a top-level parameter or set here
        ) router_inst (
          .from_col    (gc[$clog2(NUM_COLS)-1:0]),
          .from_row    (gr[$clog2(Z)-1:0]),
          .from_layer  (current_layer),
          .to_row      (router_to_row[gc][gr]),
          .active      (router_active[gc][gr]),
          .inactive_layer(router_inactive[gc][gr])
        );
      end
    end
  endgenerate

  // --- Combinational routing logic ---
  // For each column c and row r: route layer_bus_out_flat[c][r*MSG_W +: MSG_W]
  // to layer_bus_in_flat[next_col][dest_row*MSG_W +: MSG_W] based on router outputs.
  // Behavior:
  //   inactive_layer == 1 -> no connection (leave destination zero)
  //   router_active == 0 && !inactive -> bypass: same-row copy
  //   router_active == 1 -> active shift routing to dest row

  integer i, j;
  always_comb begin
    // default all inputs to zero (deterministic)
    for (i = 0; i < NUM_COLS; i = i + 1) begin
      layer_bus_in_flat[i] = { (Z*MSG_W){1'b0} };
    end

    // route
    for (i = 0; i < NUM_COLS; i = i + 1) begin
      int next_col = (i + 1) % NUM_COLS;
      for (j = 0; j < Z; j = j + 1) begin
        // source slice message index (flat)
        int src_idx = j * MSG_W;
        if (router_inactive[i][j]) begin
          // inactive wired layer: no destination; leave as zero
        end
        else if (!router_active[i][j]) begin
          // bypass (all-zero): forward same-row
          layer_bus_in_flat[next_col][src_idx +: MSG_W] =
            layer_bus_out_flat[i][src_idx +: MSG_W];
        end
        else begin
          // active: route to shifted destination row
          int dest = router_to_row[i][j];
          int dst_idx = dest * MSG_W;
          layer_bus_in_flat[next_col][dst_idx +: MSG_W] =
            layer_bus_out_flat[i][src_idx +: MSG_W];
        end
      end
    end
  end

  // Done-all: simple reduction of frame_done (all frames completed)
  assign done_all = &frame_done;

  // Placeholder: frame_done must be generated by parity checker logic.
  // For now it remains a reg; connect your parity reduction to set frame_done[frame_idx].
endmodule